//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrawledUrlsTable
    {
        public string UrlHash { get; set; }
        public string UrlName { get; set; }
        public System.DateTime DiscoverDate { get; set; }
        public short LinkDepthLevel { get; set; }
        public string ParentUrlHash { get; set; }
        public System.DateTime LastCrawlingDate { get; set; }
        public string SourceCode { get; set; }
        public int FetchedTime { get; set; }
        public string CrawledPageTitle { get; set; }
        public byte CompressionPercent { get; set; }
        public bool IsCrawled { get; set; }
        public string HostUrl { get; set; }
        public byte TryCounter { get; set; }
        public bool BlockThisUrl { get; set; }
        public string OriginUrl { get; set; }
        public bool Failed { get; set; }
        public System.DateTime LastTryDate { get; set; }
    }
}
